### ISSUE TITLE
Site Pagination

### ISSUE THREAD

**Issue by ocassidydev** [ocassidydev/chef-mate#1]
As a **Site User** I can **view a paginated list of recipes** so that **easily select a recipe to view**

##Acceptance Criteria

-The site landing page displays a scrollable list of 10 recipe cards
-The user can easily navigate this, and click to display the next page of 10 recipes

##Tasks

- [ ] Create logic in views.py
- [ ] Create index.html with information display
- [ ] Link the display and view in urls.py
