### ISSUE TITLE
Recipe post

### ISSUE THREAD

**Issue by ocassidydev** [ocassidydev/chef-mate#2]
As a **User** I can **click on a recipe card** so that **I can view the recipe in detail**

##Acceptance Criteria

-Recipe cards on the landing page are all anchored to generated pages containing the information on the recipes from the database
-It is easy to navigate back to the landing page from a recipe page
-Navigating back to the paginated landing page leaves the user in the same position as they were when they clicked in

##Tasks

- [ ] Implement necessary logic in the views.py file
- [ ] Create recipe.html page to display recipe information
- [ ] Link recipe.html to its respective view in the urls.py file
