### ISSUE TITLE
Create New Recipe

### ISSUE THREAD

**Issue by ocassidydev** [ocassidydev/chef-mate#6]
As a **Site Admin** I can **add new recipes to the site via the admin panel** so that **I can initially populate the site with recipes for the users to start with**

##Acceptance Criteria

-Interface on admin panel for adding a new recipes
-Clearly allows inputting necessary information to display it (title, ingredients, etc.)

##Tasks

- [x] Implement Recipe class in models.py
- [x] Register Recipe model in admin.py
- [x] Use the summernote library to create an easy to use page for adding a new recipe

Must have
